/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import FUINormalFish from "./FUINormalFish";
import FUIRoomView from "./FUIRoomView";
import FUIBackgroundView from "./FUIBackgroundView";
import FUIFishContent from "./FUIFishContent";
import FUIBullet from "./FUIBullet";
import FUIBulletView from "./FUIBulletView";
import FUIBatteryView from "./FUIBatteryView";
import FUIAutoHuntTipsView from "./FUIAutoHuntTipsView";
import FUIautoHuntSelectBtn from "./FUIautoHuntSelectBtn";
import FUInet from "./FUInet";
import FUIAutoHuntingView from "./FUIAutoHuntingView";
import FUIAutoFireFishItem from "./FUIAutoFireFishItem";
import FUIloadConfigBtn from "./FUIloadConfigBtn";
import FUIchangeConfigBtn from "./FUIchangeConfigBtn";
import FUIRoomTipsView from "./FUIRoomTipsView";
import FUIbatteryLvBtn from "./FUIbatteryLvBtn";
import FUIPlayerInfoView from "./FUIPlayerInfoView";
import FUIlockBtn from "./FUIlockBtn";
import FUIunLockBtn from "./FUIunLockBtn";
import FUIPlayerGunView from "./FUIPlayerGunView";
import FUILoopBackgroundView_1 from "./FUILoopBackgroundView_1";
import FUITriStarFish from "./FUITriStarFish";
import FUIFourFish from "./FUIFourFish";
import FUIgun from "./FUIgun";
import FUIwinGoldNumView from "./FUIwinGoldNumView";
import FUIcatchAllLineView from "./FUIcatchAllLineView";
import FUIContentView from "./FUIContentView";
import FUIcloseBtn from "./FUIcloseBtn";
import FUIselectBtn from "./FUIselectBtn";
import FUIcontent from "./FUIcontent";
import FUIFishDeadTipsView from "./FUIFishDeadTipsView";
import FUImenuBtn from "./FUImenuBtn";
import FUImenuView from "./FUImenuView";
import FUIsettingBtn from "./FUIsettingBtn";
import FUImenuBtnListView from "./FUImenuBtnListView";
import FUIAimLineView from "./FUIAimLineView";
import FUIhuntingFishItem from "./FUIhuntingFishItem";
import FUITipsView from "./FUITipsView";
import FUIwaveAniView from "./FUIwaveAniView";
import FUILoopBackgroundView_2 from "./FUILoopBackgroundView_2";
import FUIFullScreenGoldAniView from "./FUIFullScreenGoldAniView";
import FUIGoldListItemView from "./FUIGoldListItemView";
import FUIShowGoldListView from "./FUIShowGoldListView";
import FUIGuideView from "./FUIGuideView";

export default class roomSceneBinder{
	public static bindAll():void {
		fairygui.UIObjectFactory.setPackageItemExtension(FUINormalFish.URL, FUINormalFish);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIRoomView.URL, FUIRoomView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIBackgroundView.URL, FUIBackgroundView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIFishContent.URL, FUIFishContent);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIBullet.URL, FUIBullet);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIBulletView.URL, FUIBulletView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIBatteryView.URL, FUIBatteryView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIAutoHuntTipsView.URL, FUIAutoHuntTipsView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIautoHuntSelectBtn.URL, FUIautoHuntSelectBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUInet.URL, FUInet);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIAutoHuntingView.URL, FUIAutoHuntingView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIAutoFireFishItem.URL, FUIAutoFireFishItem);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIloadConfigBtn.URL, FUIloadConfigBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIchangeConfigBtn.URL, FUIchangeConfigBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIRoomTipsView.URL, FUIRoomTipsView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIbatteryLvBtn.URL, FUIbatteryLvBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIPlayerInfoView.URL, FUIPlayerInfoView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIlockBtn.URL, FUIlockBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIunLockBtn.URL, FUIunLockBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIPlayerGunView.URL, FUIPlayerGunView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUILoopBackgroundView_1.URL, FUILoopBackgroundView_1);
		fairygui.UIObjectFactory.setPackageItemExtension(FUITriStarFish.URL, FUITriStarFish);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIFourFish.URL, FUIFourFish);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIgun.URL, FUIgun);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIwinGoldNumView.URL, FUIwinGoldNumView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIcatchAllLineView.URL, FUIcatchAllLineView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIContentView.URL, FUIContentView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIcloseBtn.URL, FUIcloseBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIselectBtn.URL, FUIselectBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIcontent.URL, FUIcontent);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIFishDeadTipsView.URL, FUIFishDeadTipsView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUImenuBtn.URL, FUImenuBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUImenuView.URL, FUImenuView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIsettingBtn.URL, FUIsettingBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(FUImenuBtnListView.URL, FUImenuBtnListView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIAimLineView.URL, FUIAimLineView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIhuntingFishItem.URL, FUIhuntingFishItem);
		fairygui.UIObjectFactory.setPackageItemExtension(FUITipsView.URL, FUITipsView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIwaveAniView.URL, FUIwaveAniView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUILoopBackgroundView_2.URL, FUILoopBackgroundView_2);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIFullScreenGoldAniView.URL, FUIFullScreenGoldAniView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIGoldListItemView.URL, FUIGoldListItemView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIShowGoldListView.URL, FUIShowGoldListView);
		fairygui.UIObjectFactory.setPackageItemExtension(FUIGuideView.URL, FUIGuideView);
	}
}